const FETCH_ALL_STORIES = 'FETCH_ALL_STORIES';
const FETCH_USER_STORIES = 'FETCH_USER_STORIES';
const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS';
const FETCH_STORIES_BY_TAG = 'FETCH_STORIES_BY_TAG';
const CREATE_STORY = 'CREATE_STORY';
const UPDATE_USER = 'UPDATE_USER';
const DELETE_USER = 'DELETE_USER';
const DELETE_USER_STORIES = 'DELETE_USER_STORIES';
const DELETE_USER_COMMENTS = 'DELETE_USER_COMMENTS';
const DELETE_STORY = 'DELETE_STORY';
const AUTHENTICATION = 'AUTHENTICATION';
const UPDATE_STORY = 'UPDATE_STORY';
const LOGOUT = 'LOGOUT';
const OPEN_DASHBOARD = 'OPEN_DASHBOARD';
const FETCH_PROFILE = 'FETCH_PROFILE';
const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';

export {
  FETCH_ALL_STORIES,
  FETCH_USER_STORIES,
  FETCH_ALL_TAGS,
  FETCH_STORIES_BY_TAG,
  CREATE_STORY,
  UPDATE_STORY,
  DELETE_STORY,
  DELETE_USER_STORIES,
  AUTHENTICATION,
  UPDATE_USER,
  DELETE_USER,
  LOGOUT,
  OPEN_DASHBOARD,
  FETCH_PROFILE,
  UPLOAD_PROFILE_IMAGE,
  DELETE_USER_COMMENTS,
};
