export const users = [
  {
    username: 'john_doe',
    role: 'admin',
    birthdate: '1990-05-15',
    gender: 'male',
    bio: 'Tech enthusiast and blogger.',
    style: 'minimalist',
    posts: 0,
    email: 'pw.john.doe@example.com',
    password: 'hashed_password_1',
  },
  {
    username: 'jane_smith',
    role: 'user',
    birthdate: '1995-09-22',
    gender: 'female',
    bio: 'Loves photography and travel.',
    style: 'bohemian',
    posts: 0,
    email: 'pw.jane.smith@example.com',
    password: 'hashed_password_2',
  },
  {
    username: 'alice_wonder',
    role: 'moderator',
    birthdate: '1988-03-10',
    gender: 'female',
    bio: 'Community manager and writer.',
    style: 'vintage',
    posts: 0,
    email: 'pw.alice.wonder@example.com',
    password: 'hashed_password_3',
  },
  {
    username: 'bob_builder',
    role: 'user',
    birthdate: '1985-07-29',
    gender: 'male',
    bio: 'DIY enthusiast and woodworker.',
    style: 'industrial',
    posts: 0,
    email: 'pw.bob.builder@example.com',
    password: 'hashed_password_4',
  },
  {
    username: 'charlie_dev',
    role: 'admin',
    birthdate: '1992-11-05',
    gender: 'male',
    bio: 'Full-stack developer and open-source contributor.',
    style: 'modern',
    posts: 30,
    email: 'pw.charlie.dev@example.com',
    password: 'hashed_password_5',
  },
];
